name: Validation

on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Attempt Rendering of Documentation for Validation
        uses: openactive/extension-documentation-generator@master
        with:
          header: header.md
          context: test-interface.jsonld
          with_issues: false
